apiVersion: v1alpha1
kind: BridgeConfig
name: br0
hardwareAddr: 78:55:36:08:cd:fe
links:
  - enp3s0
  - enp2s0
stp:
  enabled: true
up: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: br0
clientIdentifier: mac
