apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-ca
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: system
  source:
    repoURL: https://github.com/serhii-myronets/homelab.git
    targetRevision: main
    path: core-talos/03-gitops/components/system/security/home-ca
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
