apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer.yaml
  - certificate.yaml
  - ca-server.yaml
configMapGenerator:
  - name: ca-server
    files:
      - web/index.html
      - nginx.conf=web/nginx.conf
    options:
      disableNameSuffixHash: true
