services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.home,serhii.link
      TZ: America/Los_Angeles
    volumes:
      - ./config:/app/config:ro
    tmpfs:
      - /app/config/logs
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true
