openebs-crds:
  csi:
    volumeSnapshots:
      enabled: false

localpv-provisioner:
  enabled: true
  hostpathClass:
    name: fast-local
    isDefaultClass: false
    basePath: /var/mnt/cache/openebs
    reclaimPolicy: Retain

engines:
  local:
    hostpath:
      enabled: true
    lvm:
      enabled: false
    rawfile:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

alloy:
  enabled: false

loki:
  enabled: false

preUpgradeHook:
  enabled: false
