apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: lvm
  resources:
    requests:
      storage: CAPACITY
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: data-restore
