apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-a
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: samba-hdd-a
  resources:
    requests:
      storage: 9000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-b
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: samba-hdd-b
  resources:
    requests:
      storage: 9000Gi
