apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: media
  annotations:
    lbipam.cilium.io/ips: 192.168.8.16
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
    - name: smb
      port: 445
      targetPort: smb
