# The bar across the top.
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: core
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
