apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rest-server
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./core/03-gitops/apps/system/storage/rest-server/app
  prune: true
  # Its repository lives on lvm-worker-1.
  dependsOn:
  - name: openebs-classes
