apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloud
  target:
    name: r2-credentials
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef: {key: /backups/R2/ACCESS_KEY_ID}
    - secretKey: SECRET_ACCESS_KEY
      remoteRef: {key: /backups/R2/SECRET_ACCESS_KEY}
