apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-hdd-a
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 9000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  claimRef:
    namespace: jellyfin
    name: hdd-a
  local:
    path: /var/mnt/hdd-a
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: homelab/media-hdd
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-apps
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  claimRef:
    namespace: jellyfin
    name: apps
  hostPath:
    path: /var/mnt/apps/jellyfin
    type: DirectoryOrCreate
