# =========================
# CORE
# =========================

kubeProxyReplacement: true

ipam:
  mode: kubernetes

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

# =========================
# PLATFORM FEATURES
# =========================

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

envoy:
  enabled: true

# =========================
# LOAD BALANCER
# =========================

l2announcements:
  enabled: true

# devices:
#   - eth0
