apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nordvpn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloud
  target:
    name: nordvpn
  data:
    - secretKey: OPENVPN_USER
      remoteRef: {key: /nordvpn/OPENVPN_USER}
    - secretKey: OPENVPN_PASSWORD
      remoteRef: {key: /nordvpn/OPENVPN_PASSWORD}
