apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-a
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: torrent-hdd-a
  resources:
    requests:
      storage: 9000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: torrent-apps
  resources:
    requests:
      storage: 5Gi
