apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - helmrelease.yaml
  - httproute.yaml
  - ingest.yaml
  - otel-collector.yaml
  - otel-collector-rules.yaml
  - cluster-rules.yaml
  - router-scrape.yaml
