apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cloud
  target:
    name: adguard-credentials
  data:
    - secretKey: USERNAME
      remoteRef: {key: /system/adguard/USERNAME}
    - secretKey: PASSWORD
      remoteRef: {key: /system/adguard/PASSWORD}
