apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- namespace.yaml
- externalsecret-cloudflare.yaml
- helmrelease-cloudflare.yaml
- externalsecret-rfc2136.yaml
- helmrelease-rfc2136.yaml
