server {
    listen 80;
    root /usr/share/nginx/html;

    location = /root.crt {
        types { } default_type application/x-x509-ca-cert;
        add_header Content-Disposition 'attachment; filename="homelab-root.crt"';
    }
}
